name: Build DeluxeManager Windows

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Application
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Windows Release
        run: flutter build windows --release
      
      - name: Package Windows Application
        run: |
          $buildPath = "build\windows\x64\runner\Release"
          $appName = "deluxemanager-windows-v1.0.0"
          
          # Crear carpeta para empaquetado
          New-Item -ItemType Directory -Path $appName -Force
          
          # Copiar archivos de la aplicación
          Copy-Item -Path "$buildPath\*" -Destination $appName -Recurse
          
          # Crear ZIP
          Compress-Archive -Path $appName -DestinationPath "$appName.zip" -Force
          
          # Mostrar información
          Write-Host "✓ Application packaged successfully"
          Get-ChildItem "$appName.zip" | Format-List Name, Length, LastWriteTime
        shell: powershell
      
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: deluxemanager-windows-release
          path: deluxemanager-windows-v1.0.0.zip
          retention-days: 30
